// <auto-generated />
using System;
using ECommerce.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250603153528_DBUpdate")]
    partial class DBUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("560a88f4-f3e5-40e6-8076-5cd6780dc14a"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 0m,
                            UserId = new Guid("d1407a13-ad60-48ad-8346-8fba9cbb4f41")
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3156994b-be86-4e69-b0c3-b383ab203a12"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các loại điện thoại",
                            Name = "Điện thoại"
                        },
                        new
                        {
                            Id = new Guid("a9ea7cd2-f475-4a7c-9f25-7116f4073c64"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Máy tính xách tay",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = new Guid("a02a5c5a-f789-4bfe-abff-064ded0a2cde"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe, sạc, v.v.",
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = new Guid("878dfce8-75e5-4a2b-ba2f-a05322e18239"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Máy lạnh, tủ lạnh",
                            Name = "Đồ gia dụng"
                        },
                        new
                        {
                            Id = new Guid("296a460b-3216-4557-983c-58c58d87fdf7"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Các loại tivi, màn hình",
                            Name = "TV & Màn hình"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Coupon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CouponType")
                        .HasColumnType("int");

                    b.Property<decimal>("CouponValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("StripePaymentIntentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payment", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d57fc2b6-0dc6-4a88-bbaf-bb876aa14310"),
                            Description = "View user information",
                            Name = "View.User"
                        },
                        new
                        {
                            Id = new Guid("6610746a-389f-472e-b4eb-5eef6295b361"),
                            Description = "Update user information",
                            Name = "Update.User"
                        },
                        new
                        {
                            Id = new Guid("ccaaebbd-4740-4516-b860-f6440fd4c55f"),
                            Description = "Delete user",
                            Name = "Delete.User"
                        },
                        new
                        {
                            Id = new Guid("238ec90a-8408-4fbe-a991-eb8f2eb4a28c"),
                            Description = "View cart",
                            Name = "View.Cart"
                        },
                        new
                        {
                            Id = new Guid("b248903f-6891-4ebb-8b33-55a3dfa879df"),
                            Description = "Update cart",
                            Name = "Update.Cart"
                        },
                        new
                        {
                            Id = new Guid("8c711aad-83b0-4e9e-af6d-b406ca1b150d"),
                            Description = "Delete cart",
                            Name = "Delete.Cart"
                        },
                        new
                        {
                            Id = new Guid("22a895e7-40ac-4168-bc64-def6c6e945a6"),
                            Description = "View order",
                            Name = "View.Order"
                        },
                        new
                        {
                            Id = new Guid("b764954a-903a-4ec2-ac11-988e2f9f22ae"),
                            Description = "Create order",
                            Name = "Create.Order"
                        },
                        new
                        {
                            Id = new Guid("02cd1655-929b-437b-98e5-8a6551eae34d"),
                            Description = "Update order",
                            Name = "Update.Order"
                        },
                        new
                        {
                            Id = new Guid("c5c65040-fd76-440f-bec0-51f86f19e431"),
                            Description = "Delete order",
                            Name = "Delete.Order"
                        },
                        new
                        {
                            Id = new Guid("b84f9ad1-b64f-40b7-8fb2-f71c44ef0106"),
                            Description = "Approve order",
                            Name = "Approve.Order"
                        },
                        new
                        {
                            Id = new Guid("b898cc6c-762e-40d4-9a9c-0cd1a3eb7b8e"),
                            Description = "View order item",
                            Name = "View.OrderItem"
                        },
                        new
                        {
                            Id = new Guid("b4c24c83-5628-4a9f-834b-10b07147481d"),
                            Description = "Update order item",
                            Name = "Update.OrderItem"
                        },
                        new
                        {
                            Id = new Guid("e95657da-49a6-49fc-8d6f-384a2dc45cce"),
                            Description = "View product",
                            Name = "View.Product"
                        },
                        new
                        {
                            Id = new Guid("7b61a427-65a7-459f-a0ed-41154bfaadf5"),
                            Description = "Create product",
                            Name = "Create.Product"
                        },
                        new
                        {
                            Id = new Guid("a3ac9aaa-f16a-4100-b07b-e0d4897193db"),
                            Description = "Update product",
                            Name = "Update.Product"
                        },
                        new
                        {
                            Id = new Guid("61d6359f-ce94-4d20-b2d7-66d03ff92891"),
                            Description = "Delete product",
                            Name = "Delete.Product"
                        },
                        new
                        {
                            Id = new Guid("86685765-75fd-4f6d-9f05-46c65ada32d8"),
                            Description = "View category",
                            Name = "View.Category"
                        },
                        new
                        {
                            Id = new Guid("e1532412-29c1-4e1c-afbf-0f5c5c4e41df"),
                            Description = "Create category",
                            Name = "Create.Category"
                        },
                        new
                        {
                            Id = new Guid("00cff030-2921-4267-b802-86dc6d88174a"),
                            Description = "Update category",
                            Name = "Update.Category"
                        },
                        new
                        {
                            Id = new Guid("3759092e-5e7b-4ca2-8c83-33104f549a0a"),
                            Description = "Delete category",
                            Name = "Delete.Category"
                        },
                        new
                        {
                            Id = new Guid("fa8fed50-24a7-4871-84d7-20b2376e8e27"),
                            Description = "View payment",
                            Name = "View.Payment"
                        },
                        new
                        {
                            Id = new Guid("aeb40204-4004-4884-b510-e46742046698"),
                            Description = "Create payment",
                            Name = "Create.Payment"
                        },
                        new
                        {
                            Id = new Guid("fcadd358-388c-4d20-a5af-86a235cf4352"),
                            Description = "Update payment",
                            Name = "Update.Payment"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c107fe9b-ae3e-4b74-bb43-0d390c79d486"),
                            CategoryId = new Guid("3156994b-be86-4e69-b0c3-b383ab203a12"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Điện thoại cao cấp với camera 48MP và chip A16 Bionic",
                            Name = "iPhone 14 Pro",
                            Price = 27990000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("f19411a4-e9dd-41af-9773-73051ab930a5"),
                            CategoryId = new Guid("3156994b-be86-4e69-b0c3-b383ab203a12"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartphone flagship với bút S-Pen và camera 200MP",
                            Name = "Samsung S23 Ultra",
                            Price = 30990000m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("4e3d18ea-474a-4a7d-96d9-89e6545d626b"),
                            CategoryId = new Guid("a02a5c5a-f789-4bfe-abff-064ded0a2cde"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tai nghe không dây với chất lượng âm thanh tốt và chống ồn chủ động",
                            Name = "Tai nghe AirPods",
                            Price = 4990000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("a1034129-c1fd-42d5-9773-b878fde40e1a"),
                            CategoryId = new Guid("a9ea7cd2-f475-4a7c-9f25-7116f4073c64"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ultrabook cao cấp với màn hình 4K OLED và CPU Intel Core i9",
                            Name = "Dell XPS 15",
                            Price = 45990000m,
                            StockQuantity = 25
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product_Coupons", b =>
                {
                    b.Property<Guid>("CouponId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CouponId", "ProductId");

                    b.ToTable("Product_Coupons", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("a6f25e26-400e-4e55-97b3-94ac35fd32ee"),
                            Name = "Customer"
                        },
                        new
                        {
                            Id = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d"),
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermission", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("d57fc2b6-0dc6-4a88-bbaf-bb876aa14310")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("6610746a-389f-472e-b4eb-5eef6295b361")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("ccaaebbd-4740-4516-b860-f6440fd4c55f")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("238ec90a-8408-4fbe-a991-eb8f2eb4a28c")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("b248903f-6891-4ebb-8b33-55a3dfa879df")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("8c711aad-83b0-4e9e-af6d-b406ca1b150d")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("22a895e7-40ac-4168-bc64-def6c6e945a6")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("b764954a-903a-4ec2-ac11-988e2f9f22ae")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("02cd1655-929b-437b-98e5-8a6551eae34d")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("c5c65040-fd76-440f-bec0-51f86f19e431")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("b84f9ad1-b64f-40b7-8fb2-f71c44ef0106")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("b898cc6c-762e-40d4-9a9c-0cd1a3eb7b8e")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("b4c24c83-5628-4a9f-834b-10b07147481d")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("e95657da-49a6-49fc-8d6f-384a2dc45cce")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("7b61a427-65a7-459f-a0ed-41154bfaadf5")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("a3ac9aaa-f16a-4100-b07b-e0d4897193db")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("61d6359f-ce94-4d20-b2d7-66d03ff92891")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("86685765-75fd-4f6d-9f05-46c65ada32d8")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("e1532412-29c1-4e1c-afbf-0f5c5c4e41df")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("00cff030-2921-4267-b802-86dc6d88174a")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("3759092e-5e7b-4ca2-8c83-33104f549a0a")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("fa8fed50-24a7-4871-84d7-20b2376e8e27")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("aeb40204-4004-4884-b510-e46742046698")
                        },
                        new
                        {
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf"),
                            PermissionId = new Guid("fcadd358-388c-4d20-a5af-86a235cf4352")
                        },
                        new
                        {
                            RoleId = new Guid("a6f25e26-400e-4e55-97b3-94ac35fd32ee"),
                            PermissionId = new Guid("22a895e7-40ac-4168-bc64-def6c6e945a6")
                        },
                        new
                        {
                            RoleId = new Guid("a6f25e26-400e-4e55-97b3-94ac35fd32ee"),
                            PermissionId = new Guid("b764954a-903a-4ec2-ac11-988e2f9f22ae")
                        },
                        new
                        {
                            RoleId = new Guid("a6f25e26-400e-4e55-97b3-94ac35fd32ee"),
                            PermissionId = new Guid("238ec90a-8408-4fbe-a991-eb8f2eb4a28c")
                        },
                        new
                        {
                            RoleId = new Guid("a6f25e26-400e-4e55-97b3-94ac35fd32ee"),
                            PermissionId = new Guid("b248903f-6891-4ebb-8b33-55a3dfa879df")
                        },
                        new
                        {
                            RoleId = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d"),
                            PermissionId = new Guid("22a895e7-40ac-4168-bc64-def6c6e945a6")
                        },
                        new
                        {
                            RoleId = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d"),
                            PermissionId = new Guid("02cd1655-929b-437b-98e5-8a6551eae34d")
                        },
                        new
                        {
                            RoleId = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d"),
                            PermissionId = new Guid("b84f9ad1-b64f-40b7-8fb2-f71c44ef0106")
                        },
                        new
                        {
                            RoleId = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d"),
                            PermissionId = new Guid("e95657da-49a6-49fc-8d6f-384a2dc45cce")
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1407a13-ad60-48ad-8346-8fba9cbb4f41"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Thanh123@gmail.com",
                            Name = "Thanh",
                            Password = "$2a$11$0/CP8hh.odVCJCJi0d261ObBVpXQ06FuX53Aiq6Fn.0pKKdcdnMz2",
                            Phone = "0985632147"
                        },
                        new
                        {
                            Id = new Guid("35e3a23d-4ac9-4282-89e9-5ea690da8458"),
                            CreatedAt = new DateTime(2024, 3, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minhquang85213@gmail.com",
                            Name = "Quang",
                            Password = "$2a$11$FkdaLqGjhB0K5sPGuD71NOa0ggTcYkn/R.b8UWBKbHyxRSBruexR.",
                            Phone = "0789653241"
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("d1407a13-ad60-48ad-8346-8fba9cbb4f41"),
                            RoleId = new Guid("4ea25da4-9081-41f8-83ba-2ba6e047fcbf")
                        },
                        new
                        {
                            UserId = new Guid("35e3a23d-4ac9-4282-89e9-5ea690da8458"),
                            RoleId = new Guid("fcd2fb03-484d-4c67-9940-bf4668619e9d")
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("ECommerce.Domain.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.CartItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Payment", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("ECommerce.Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product_Coupons", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Coupon", "Coupon")
                        .WithMany("Product_Coupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Product", "Product")
                        .WithMany("Product_Coupons")
                        .HasForeignKey("CouponId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("ECommerce.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Coupon", b =>
                {
                    b.Navigation("Product_Coupons");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("Product_Coupons");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ECommerce.Domain.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
